### ISSUE TITLE
Details Page Outcrop

### ISSUE THREAD

**Issue by rene-fas** [rene-fas/capstone#1]
Value proposition:

as a user
i want to view a detailpage of one outcrop
in order to take notes and remember details

Description
![OutcropDetailsPage](https://github.com/rene-fas/backend-create_products/assets/130792389/fb904232-8e44-46b7-8454-1a0db4ff99d9)

Acceptance criteria
 - [x] every inputfield has a visible label.
 - [x] user can see different form fields to write notes 
 - [x] user can submit the data
 - [x] submitted data is displayed as text below the form
 - [x] heading always visible

Tasks
 - [x] create a branch
 - [x] create a page
 - [x] create a heading with a title
 - [x] create a form with various textfields
 - [x] prevent event.default() on submit
 - [x] create a list with given entries out of the form on submit
​

**Comment by julialoeschel** [comment]
Hey! 
I have some thoughts on this: 
- the + button has no function - we dont need it here
- what information are displayed on the list? names or locations, or both? 
- you could create dummy data here and avoid hardcoding, this would be a good chance to think about the structure :) 

other than that: great job!

**Comment by julialoeschel** [comment]
Great choice. 
I suggest to scribble the Labels for the input fields as well(remember: we always have a label for every input field to indicate the user what to write). 
The interpretation/Discussion looks like a textarea (if you expect the user to write longer text, plan it ahead) 

other than that, this is a very good story

**Comment by julialoeschel** [comment]
🚀 
sehr gut! 
so passt es !
