### ISSUE TITLE
add new outcrops

### ISSUE THREAD

**Issue by rene-fas** [rene-fas/capstone#10]
Value proposition:

as a user
i want to be able to add new outcrops
in order to further advance the collection

Description

![Image](https://github.com/rene-fas/capstone/assets/130792389/838ec79c-b496-4393-b1c7-c850efa53066)

Acceptance criteria

 - [ ] there is an add button on the Outcroplist
 - [ ] clicking the add button results in opening a popup with a inputfield for a title and a cancel + add button
 - [ ] clicking cancel results in closing the popup wherefore pressing the add button results in adding a outcrop within the
        entered list and closing the popup
 - [ ] newly added list entries should be clickable aswell to redirect you to the corresponding outcropdetails page and have 
        the correct title

Tasks

 - [ ] create a branch
 - [ ] create an add button (+)
 - [ ] implement popup on click logic
 - [ ] implement cancel + add button click logic in popupform

**Comment by actyvystom** [comment]
A nice one! 
Although the wireframe looks a bit confusing at first glance, it makes total sense when reading the acceptance criteria.
lgtm ✅ 
Cheers, Thomas
