### ISSUE TITLE
delete outcrops/fieldtrips

### ISSUE THREAD

**Issue by rene-fas** [rene-fas/capstone#11]
Value proposition:

as a user
i want to be able to delete outcrops/fieldtrips
in order to have more control over the lists

Description

![Image](https://user-images.githubusercontent.com/130792389/250051757-5f85acfa-1bac-4b08-b319-8c6e1793b093.png)

Acceptance criteria

 - [ ] there is an remove button on the Outcrop- / Fieldtriplist
 - [ ] clicking the remove button results in deleting the corresponding entry

Tasks

 - [ ] create a branch
 - [ ] create a remove button (-)
 - [ ] implement remove on click logic

**Comment by MariaRiosNavarro** [comment]
short and clear, LGFM🚀
