### ISSUE TITLE
edit outcroplist/fieldtrip entries

### ISSUE THREAD

**Issue by rene-fas** [rene-fas/capstone#12]
Value proposition:

as a user
i want to be able to change the list entries
in order to have more control of the listed entries

Description

![Image](https://user-images.githubusercontent.com/130792389/250052792-ec693e86-2772-4218-af2a-6e51b34a4200.png)

Acceptance criteria

 - [ ] there is an edit button on each list
 - [ ] clicking the edit button results in opening a popup with a inputfield for a title and a cancel + edit button
 - [ ] clicking cancel results in closing the popup wherefore pressing the edit button results in editing the corresponding 
        entry within the entered list and closing the popup

Tasks

 - [ ] create a branch
 - [ ] create an edit button 
 - [ ] implement popup on click logic
 - [ ] implement cancel + edit button click logic in popupform

**Comment by actyvystom** [comment]
Also a nice one!
Just some tiny remark: try to avoid technical language in title and value proposition like `outcroplist` / `listitems`, e.g.
> As a user 
> I want to be able to edit stored outcrops
> in order to change them anytime
Cheers, Thomas

**Comment by MariaRiosNavarro** [comment]
LGFM 🚀
