### ISSUE TITLE
editable textfields on the outcropdetailspage

### ISSUE THREAD

**Issue by rene-fas** [rene-fas/capstone#13]
Value proposition:

as a user
i want to have changeable text fields on the details page
in order to have more control of my notes

Description

![Image](https://user-images.githubusercontent.com/130792389/250059995-2f35e228-7db1-4b53-a687-bf68cf98d349.png)

Acceptance criteria

 - [ ] clicking on a textfield results in a possible input
 - [ ] pressing enter / switching / loosing focus of the textfield results in saving the input
 - [ ] the saved inputs are persistent

Tasks

 - [ ] create a branch
 - [ ] switch previous input fields with editable persistent fields 
 - [ ] implement popup editable textfieldlogic

**Comment by actyvystom** [comment]
Also a nice one!
Same comment as on [US7](https://github.com/rene-fas/capstone/issues/12) 😉 
Less technical suggestion:

> as a user
> i want to be able to edit already saved texts for an outcrop
> in order to have more control of my notes

Cheers, Thomas

**Comment by MariaRiosNavarro** [comment]
LGFM🚀
