### ISSUE TITLE
add photos on outcropdetailspage

### ISSUE THREAD

**Issue by rene-fas** [rene-fas/capstone#18]
Value proposition:

as a user
i want to implement photos in my notes
in order to have a visual addition to the text notes

Description

![Image](https://user-images.githubusercontent.com/130792389/252331502-de63019d-4147-4d38-b24f-2f97196d83d9.png)

Acceptance criteria

 - [ ]  a button to add photos is on the details page
 - [ ]  clicking the add photo button results in opening a file browser to choose which photo you want to add
 - [ ] the chosen photo for the upload has a preview so you can be sure that you chose the right one
 - [ ] added photos are displayed under the textfields

Tasks

 - [ ] create a branch
 - [ ] add a button
 - [ ] implement button logic
 - [ ] implement picture saving + displaying logic (using cloudinary to upload images + localStorage to save imagepaths) 
 - [ ] display photo(s) beneath notes

**Comment by julialoeschel** [comment]
you could mention that you will use cloudinary and if there is a preview before uploading, you should mention that too ;) 

otheriwse - great job.

**Comment by rene-fas** [comment]
I am unsure if i will use cloudinary. Usually you would do the photos of the outcrops in the field so these photos are on your phone i currently dont see the advantage of doing a probably lenghty upload of an image somewhere where you most likely dont have a wlan connection. So i was more looking into using Filereader and local Storage although i know the limitations of about 2 gb. More or less i am currently searching a fitting solution.

**Comment by CarstenJahnke** [comment]
LGTM 👍
