### ISSUE TITLE
integrate map on outcropdetailspage

### ISSUE THREAD

**Issue by rene-fas** [rene-fas/capstone#19]
Value proposition:

as a user
i want to see where my outcrop is on a map
in order to know where it exactly was

Description

![Image](https://user-images.githubusercontent.com/130792389/252333263-ea5164d8-957a-48f0-a1b2-9edbb0a4b656.png)

Acceptance criteria

 - [ ]  there is a map in front of your photos if you have added a photo else it isnt displayed
 - [ ]  on the map you can see where the photo was taken

Tasks

 - [ ] create a branch
 - [ ]  add a map (leaflet) which is displayed when there is a photo added
 - [ ] implement data fetching logic out of the first added photo (exif-data)
 - [ ] display the location on the map

**Comment by julialoeschel** [comment]
same here. 
it would be usefull to mention wich map you are gona use and where the data comes from :) 

otherwise - great stuff.

**Comment by CarstenJahnke** [comment]
LGTM 👍
