### ISSUE TITLE
List of outcrops with navigation

### ISSUE THREAD

**Issue by rene-fas** [rene-fas/capstone#2]
Value proposition:

as a user
i want to view a list of outcrops
in order to choose a specific outcrop for details

Description
![outcropNavi](https://github.com/rene-fas/capstone/assets/130792389/27e2790f-a7ab-4b8b-bb89-febd0753fe13)

Acceptance criteria
 - [ ] the user can see a list of outcrops (titles only)
 - [ ] the user can click a outcrop to be redirected to the details page
 - [ ] the user can navigate between the list and the details page
 - [ ] the details page has a working back button

Tasks
 - [x] create a branch
 - [x] create a page
 - [x] create a heading with a title
 - [x] create a list with clickable fields
 - [x] implement redirection on Click
 - [x] create a back button
 - [x] implement routes

**Comment by julialoeschel** [comment]
good story.
one thing is missing for me: 
how does the user gets back to the overview page   ?

please provide a little something to enable the user to go both ways. 

the rest is perfectly fine.

**Comment by sebastianwel** [comment]
Hey René,
agree with Julia. Now it should be fine, lgtm 🚀
