### ISSUE TITLE
Field trip list with navigation

### ISSUE THREAD

**Issue by rene-fas** [rene-fas/capstone#3]
Value proposition:

as a user
i want to have an overview of the field trips
in order to choose which field trip i want to watch

Description
![ListOfFieldtrips](https://github.com/rene-fas/capstone/assets/130792389/de4aa358-4f51-41fd-bcc5-8b4f604c4841)

Acceptance criteria
 - [ ] there is a back button on the outcrop list which redirects to the fieldtrip list on click
 - [ ] the user can see a list of field trips
 - [ ] user can click an fieldtrip title to view the outcrop list
 - [ ] user can switch between all 3 pages back and forward

Tasks
 - [ ] create a branch
 - [ ] create a footer with a back button on the outcrop list
 - [ ] implement redirection on Click
 - [ ] implement back button on the outcrop list

**Comment by julialoeschel** [comment]
AHHHH! there it is!!!! 
:) 
the back button should be included in the last US.
:octocat:

**Comment by rene-fas** [comment]
reworked us3, back button was implemented in [US2](https://github.com/rene-fas/capstone/issues/2#issue-1771109462) and removed in this US. Instead i added an overview of the fieldtrips as a list with an equivalent functionality as the outcroplist in US2.

**Comment by julialoeschel** [comment]
🚀
