### ISSUE TITLE
add new fieldtrips

### ISSUE THREAD

**Issue by rene-fas** [rene-fas/capstone#4]
Value proposition:

as a user
i want to be able to add new field trips
in order to further advance the collection

Description

![Image](https://github.com/rene-fas/capstone/assets/130792389/b05beb45-846e-48a3-a12e-239a2a6b281d)

Acceptance criteria
 - [ ] there is an add button 
 - [ ] clicking the add button results in opening a popup with inputfields and a cancel + add button
 - [ ] clicking cancel results in closing the popup wherefore pressing the add button results in adding a fieldtrip within the 
         entered list and closing the popup
 - [ ] newly added list entries should be clickable aswell to redirect you to the corresponding outcrop list and have the 
        correct title

Tasks
 - [ ] create a branch
 - [ ] create an add button (+) 
 - [ ] implement popup on click logic
 - [ ] implement cancel + add button click logic in popupform

**Comment by ghost** [comment]
I assume the Submit Button already got it's function in a previous US. The Add - Button and all that happens then seems clear to me. Nice story.

**Comment by rene-fas** [comment]
Thanks, yeah this was part of [US1](https://github.com/rene-fas/capstone/issues/1#issue-1771107024)
